---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinyauth
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tinyauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        SECRET: "{{ .TINYAUTH_SECRET }}"
        # OIDC
        TINYAUTH_PROVIDERS_POCKETID_CLIENTID: "{{ .TINYAUTH_CLIENT_ID }}"
        TINYAUTH_PROVIDERS_POCKETID_CLIENTSECRET: "{{ .TINYAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: tinyauth
    - extract:
        key: pocket-id
