---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: tinyauth
spec:
  from:
    - &policy
      group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: default
    - <<: *policy
      namespace: dev
    - <<: *policy
      namespace: gaming
    - <<: *policy
      namespace: home
    - <<: *policy
      namespace: selfhosted
    - <<: *policy
      namespace: media
    - <<: *policy
      namespace: observability
    - <<: *policy
      namespace: networking
    - <<: *policy
      namespace: ai
  to:
    - group: ""
      kind: Service
      name: tinyauth
