---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly-cluster
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dragonfly-cluster-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .DRAGONFLY_S3_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .DRAGONFLY_S3_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: dragonfly
