---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./descheduler/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
  # - ./nvidia-device-plugin/ks.yaml
  - ./generic-device-plugin/ks.yaml
components:
  - ../../components/repos
  - ../../components/substitutions
