---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync-system
resources:
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
  - ../../components/replacements
