---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./_pvc/ks.yaml
  - ./bazarr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./jellyseer/ks.yaml
  - ./navidrome/ks.yaml
  - ./wizarr/ks.yaml
  - ./feishin/ks.yaml
  - ./readarr/ks.yaml
  - ./ytdl-sub/ks.yaml
  - ./lidarr/ks.yaml
  - ./audiobookshelf/ks.yaml
  # - ./tdarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./cross-seed/ks.yaml
  - ./piped/ks.yaml
  - ./music-assistant/ks.yaml
  - ./huntarr/ks.yaml
  - ./jellystat/ks.yaml
  - ./tidarr/ks.yaml
  - ./cleanuparr/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
