[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"


[tools]
"uv" = "latest"
"pipx:flux-local" = "latest"
