apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:46/0ZWSKfUoLb2tSEp0QtVM=,iv:zPSHY/StfwbxhS+pgWn1V9Mka4hXNAh8FNcFqLJBIQo=,tag:Gf5RnaQa3El3FkGQ0ckqwg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:tYe9qcemB3cadIHTzuHyN7E=,iv:8s+lsp/bObCIBPMtnZLXqWR4T7TanhNCzF5kJgm+2Qs=,tag:osig7hdMeddOYkxVkcWeTw==,type:str]
    SECRET_DOMAIN_INTERNAL: ENC[AES256_GCM,data:U9D/LkaKUOvl8fKUwt4=,iv:rWZCBwodZiAY9FduWpqljgoC6lh57AgBHLAuPsvqIqY=,tag:bdp5OFTuHnbSyj38uo0a+w==,type:str]
    PRIVATE_DOMAIN_HOME: ENC[AES256_GCM,data:zhAAZwBN1W+JVN0b5Mk=,iv:HVVuLboHGClarnXTKzqRQhPdClsRr9rPhypvqOLQ48g=,tag:FT20DWKuHjkMi6L0lh08Qg==,type:str]
    PRIVATE_EMAIL: ENC[AES256_GCM,data:gcOm7nWa+XPhBMHEAKSzCn9m54cZQA==,iv:r1DPuElai1eb5tNV3xHqdP9eLPHRoE3UMtky23ax3Jg=,tag:yrEw0VgcWLodku3XXA2LVQ==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:m+j2xJADzzJEQHLb4Wx+AzM=,iv:gCFk/KIzQEWYaOOJO6imbwSNl6JRszPTaupYLgwCVfM=,tag:hHflrW3hVOs2OGx7vD9UQw==,type:str]
    PUBLIC_IPV6_PREFIX: ENC[AES256_GCM,data:qR2p8D4DlKKYxUuaeiA=,iv:xcMaI0gLC2fyP60JzYThD/OFt5KXm9V/I+iIldNmPxU=,tag:9zu3Ae/rigIOPzNZUvjd/A==,type:str]
sops:
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYi9UQm54TGt6OFFXTVE5
            YTVTVWVpdDNENEFYWHIzK292aHVwaktReTJBCkhQR05lU0V4WGcwUGtDblByUUhm
            U3R2aXd5THFYMHYybFo0UnhnN1dKU1UKLS0tIGVlRkt3a3JDUXl5TEZuTnRBRk53
            a0dmcnJZL3ovWUJrUG9FQ2NzKzhZZUUKqMcRHZoLl16ZDzGCijr2A0fOeQs20Hbh
            jHF+9Xtf+LBwB7xvlohfZy7W6OrO2BKOJs3DWaF2m/U2TWO8cIMcRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T07:21:58Z"
    mac: ENC[AES256_GCM,data:EfJAXf6Gx6bcoSdS7PLPr521KuMIVsRmjuu+y8LsbYBC18tkVL49UOhjHe6AyGEfP4as/zBydz1gppP4B+jkwNyFSq443jcc29C8uK+GSlPHhk/75FqdbpYyo/IkHg5FWOVlwwyamU2zpNP7ujHIZ6/mzCcK+4SXQLFYcdl1ges=,iv:zwRtzOEQ2Ipu7drC5mcfjnrOAGYBXsMVaKmQwrtHDgQ=,tag:qFRpOUPfqByTBTkJWDw7fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
