apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:Wah+o0Gw8ccN/hKNRpytzqOEXr/3nuz7bWLWI3Eet2E=,iv:ULbHvgXc+eEpkvMogWpKsrqabT8sQLckDQCUpnW84Ws=,tag:jVz5FpeRpiJV5Sgx7rdztw==,type:str]
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:ZAtNCPH/rWiO03hDvzI=,iv:iwek+3n4sR7x7GYiAiDUQm1bB4gUfMgjvDKOwrZgzXs=,tag:ESTrmnPg9RhwI+c32y6Oqw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:e/1nMe4k95MStvlgWMA9h9o=,iv:h1xsET4n8GAKF4gvIkr2Z4Ch076a7o3iDkTDPuCdt1w=,tag:6zLHcAzINqKSn4rJQoLVtw==,type:str]
    PRIVATE_DOMAIN_HOME: ENC[AES256_GCM,data:Pa205Bnt/lkldG1tYA==,iv:rM18Y9DTxXhTgLoY/ibk3KdbRsdQ0wiHxQr8Ni5dy+c=,tag:7Z+AwY2d0t7l58UX4j3okQ==,type:str]
    PRIVATE_EMAIL: ENC[AES256_GCM,data:QMO/gtFsQEB+EcOKu0IBaDbV,iv:bPhxeum9Gr9yrNc1GyD1s4W8rLGrjLN/+Yb2Z8eDlJU=,tag:aFnK2439crmcE78+AlBMGA==,type:str]
    LOCAL_DOMAIN: ENC[AES256_GCM,data:aIkqOuNJ5QYMqbjbkZ0=,iv:6xptvCGUfdtgsdGsYXdaYxVfDfQpmgcHJe2YqcAR8Dk=,tag:JnqUqE4iMBOlRkKWlrcJ6A==,type:str]
    TS_DOMAIN: ENC[AES256_GCM,data:Dx6XhX7AVxWTDl6obZZaP2YVqRE=,iv:PrILj564DAWyfsMI7bohQ1xrYTDV9zKZ5FrI2F+XYU8=,tag:lZBvT/I0McctvQQppzf+QQ==,type:str]
    TS_PRIVATE_DOMAIN: ENC[AES256_GCM,data:1V37EYI+ZTwMJPmJDizn5vk=,iv:P59KvYtXV8jZ2R1rAvaFeCEsblhv46EBQ19jyjmIK+0=,tag:ieibcnMlUcc8015WQovtRQ==,type:str]
    TS_EMAIL: ENC[AES256_GCM,data:a26KKkzzaScpy3hW2TCk20DRPCExciQ=,iv:fKeFzU2PXLKgQNjBe0Y7Sc+dOYsdqJpT6iABk5MFVpI=,tag:dsQ0hy5zl56WhKySMN+9pg==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:JtTa+FCTnwhKqOwPgCEIjL0=,iv:PMN07crU0fOg7qLDbMYQl6ToNgGbjaoIV4FlwqLHz44=,tag:iGg94T4GVsOXY+7QjAo9Mw==,type:str]
    PUBLIC_IPV6_PREFIX: ENC[AES256_GCM,data:slRRWKLfpMrfiUQ7vhs=,iv:w7ptJ9KdHrgVn+0hBRzJfczWAGENuSyVyEQUUvU7Gu0=,tag:inSWN1Y/ayLur77xf3s9fA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSGJ0WDJDZWtGWE5XR2Ji
              VHJDQXYwblBteithZFFkbHZpa0RNZG1qaHc0CjBQQkcyclJYUjRCTTArcS9GT1Q2
              djNUNGFYcVJYRUdXaHA0bnlCVXc3OGsKLS0tIFVodmFES0xvRjhEMU5PR2ZYOUxn
              eEF0aWpKTmoxNEVpRFA2SEZuamhITEkK5rI/NEjfzh/daYkfGZOCfM4hcYBB0jsR
              P0PkLqUb0tFmH8IQG9oDVZfvcAhYQzARynYF1Nsyng40g92bEjnATg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T04:03:04Z"
    mac: ENC[AES256_GCM,data:VMQ1c1O8C1eMTT4kKaAa57+c2PcTrtz73ePItXZkARiPAPA7y+zLio/8BGAQMbUB3R964hqjgTKDo0eOWZ1FOGM3Z19/R4GuhCF9QeFD8ocea3PQWFro5s9KLJVR+outiv3UimM6A0QFYqFvV+YB1taSibuilj2niWNjJbsZCRM=,iv:evRaVX5LWbMlOmJutOH93bP2m8WRK65o7f8CX9I1xT0=,tag:54W4Qkwey9LjCUBjaTqPjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
