apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:46/0ZWSKfUoLb2tSEp0QtVM=,iv:zPSHY/StfwbxhS+pgWn1V9Mka4hXNAh8FNcFqLJBIQo=,tag:Gf5RnaQa3El3FkGQ0ckqwg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:tYe9qcemB3cadIHTzuHyN7E=,iv:8s+lsp/bObCIBPMtnZLXqWR4T7TanhNCzF5kJgm+2Qs=,tag:osig7hdMeddOYkxVkcWeTw==,type:str]
    SECRET_DOMAIN_INTERNAL: ENC[AES256_GCM,data:U9D/LkaKUOvl8fKUwt4=,iv:rWZCBwodZiAY9FduWpqljgoC6lh57AgBHLAuPsvqIqY=,tag:bdp5OFTuHnbSyj38uo0a+w==,type:str]
    PRIVATE_DOMAIN_HOME: ENC[AES256_GCM,data:zhAAZwBN1W+JVN0b5Mk=,iv:HVVuLboHGClarnXTKzqRQhPdClsRr9rPhypvqOLQ48g=,tag:FT20DWKuHjkMi6L0lh08Qg==,type:str]
    PRIVATE_EMAIL: ENC[AES256_GCM,data:gcOm7nWa+XPhBMHEAKSzCn9m54cZQA==,iv:r1DPuElai1eb5tNV3xHqdP9eLPHRoE3UMtky23ax3Jg=,tag:yrEw0VgcWLodku3XXA2LVQ==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:m+j2xJADzzJEQHLb4Wx+AzM=,iv:gCFk/KIzQEWYaOOJO6imbwSNl6JRszPTaupYLgwCVfM=,tag:hHflrW3hVOs2OGx7vD9UQw==,type:str]
    PUBLIC_IPV6_PREFIX: ENC[AES256_GCM,data:qR2p8D4DlKKYxUuaeiA=,iv:xcMaI0gLC2fyP60JzYThD/OFt5KXm9V/I+iIldNmPxU=,tag:9zu3Ae/rigIOPzNZUvjd/A==,type:str]
    CILIUM_LB_CIDR_V6: ENC[AES256_GCM,data:mNmx/dzHr1UJQ+ONL71x1EZreYoykA==,iv:NaNO0zV9L2QHjwsShp5FZSyoZkdRlDKtSXspjHzqg+s=,tag:YMjpfyay6dCVonOYu4b0ow==,type:str]
    CILIUM_BGP_PEER_V6: ENC[AES256_GCM,data:FYRf0rrrFFBQ3iNaihFelYI=,iv:cA+q7t6WUd3woKNPOE7EOtm/deGBWHnbUXM9Ol7b3G8=,tag:l5uSyAMQ8YCEjIzNFpXnKw==,type:str]
    INGRESS_EXT_LB_IP_V6: ENC[AES256_GCM,data:9aldPGeC6coi79u+XNUx3eC5hmzNlA==,iv:GZQjvDzsMu3MekK19EQWK4Pw+7dTnMo9tP8vOUsT/ow=,tag:FRfLpzOUmYwkD18U/bleQw==,type:str]
    INGRESS_INT_LB_IP_V6: ENC[AES256_GCM,data:dv9KX1Z1ipgTttPP6xGTldtXd87gOQ==,iv:WmF3FeumlDeftTDWgjKKvunnR2zCiiSpbrEnVLFM3QE=,tag:tC2O2XIhUc44nqa1YprR7Q==,type:str]
    INGRESS_HOME_LB_IP_V6: ENC[AES256_GCM,data:B7ai1mwUW7zGiXJeyIboPgcxl0PBIQ==,iv:JrQ9yDWTXoBnSXIAOauIol76P2OWPYWv3PLQK4liubg=,tag:+QHgEF7wYgDqw5tPQnUAaw==,type:str]
    ENVOY_INT_LB_IP_V6: ENC[AES256_GCM,data:j9PWoUT71Svr3qKypDNbPjRrDejmIQ==,iv:42VsuGjNEycrVowYR2zBtSUlqduj3kw1PZuSqbsM+sY=,tag:zd888sd2LY4xnhKyLZ0y7w==,type:str]
    ENVOY_EXT_LB_IP_V6: ENC[AES256_GCM,data:njRNlsMa85zD4CDylypug/ICuOC6Gw==,iv:oForlOij88UBGUHiQseIrWVOiqrfxzXtVfbxAKIphBc=,tag:oB2iratLPtHKEzITXIkgUw==,type:str]
    SATISFACTORY_LB_IP_V6: ENC[AES256_GCM,data:FP5ox767dY81Iqou+WQf+J73X3gz,iv:wZMkiau51B20etqkKCT0ke/hVcWkrEzsJTg1l04j98g=,tag:QwgB427idiE4LJnKPHpQXg==,type:str]
    SATISFACTORY2_LB_IP_V6: ENC[AES256_GCM,data:JnR7DETxNrPbmIHRWwOFApeaacsl,iv:EdWsHzVB9zgRlDgZyO9/6M1EE3IxZm21OnP6p9q2GAg=,tag:iSoaAOFctuQyrA9Tm12JcA==,type:str]
sops:
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYi9UQm54TGt6OFFXTVE5
            YTVTVWVpdDNENEFYWHIzK292aHVwaktReTJBCkhQR05lU0V4WGcwUGtDblByUUhm
            U3R2aXd5THFYMHYybFo0UnhnN1dKU1UKLS0tIGVlRkt3a3JDUXl5TEZuTnRBRk53
            a0dmcnJZL3ovWUJrUG9FQ2NzKzhZZUUKqMcRHZoLl16ZDzGCijr2A0fOeQs20Hbh
            jHF+9Xtf+LBwB7xvlohfZy7W6OrO2BKOJs3DWaF2m/U2TWO8cIMcRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T11:19:13Z"
    mac: ENC[AES256_GCM,data:dYH/y3ReS7nMVNvM4ml4yI1iJAWR03v9Ctb0UqSzgaYrOBoFePLMKb4L5UxIUdJzsnEso0XIfPVb3XFjXSUrRwC+fSRojkBfDj5y9ZUrlvfCB2CZJKJTzp0Eqm8Ue/v81TQZx/iO1Zi6qGWqdalFJluJBTNDiAWqzDy9nH8hkjA=,iv:yDF3K8SzBLJf0fTt+V1rE7eA2lRYouOhSFD3HPhxogU=,tag:YShVn7/5KcIQIzfophedHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
