apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:46/0ZWSKfUoLb2tSEp0QtVM=,iv:zPSHY/StfwbxhS+pgWn1V9Mka4hXNAh8FNcFqLJBIQo=,tag:Gf5RnaQa3El3FkGQ0ckqwg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:tYe9qcemB3cadIHTzuHyN7E=,iv:8s+lsp/bObCIBPMtnZLXqWR4T7TanhNCzF5kJgm+2Qs=,tag:osig7hdMeddOYkxVkcWeTw==,type:str]
    SECRET_DOMAIN_INTERNAL: ENC[AES256_GCM,data:U9D/LkaKUOvl8fKUwt4=,iv:rWZCBwodZiAY9FduWpqljgoC6lh57AgBHLAuPsvqIqY=,tag:bdp5OFTuHnbSyj38uo0a+w==,type:str]
    PRIVATE_DOMAIN_HOME: ENC[AES256_GCM,data:zhAAZwBN1W+JVN0b5Mk=,iv:HVVuLboHGClarnXTKzqRQhPdClsRr9rPhypvqOLQ48g=,tag:FT20DWKuHjkMi6L0lh08Qg==,type:str]
    PRIVATE_EMAIL: ENC[AES256_GCM,data:gcOm7nWa+XPhBMHEAKSzCn9m54cZQA==,iv:r1DPuElai1eb5tNV3xHqdP9eLPHRoE3UMtky23ax3Jg=,tag:yrEw0VgcWLodku3XXA2LVQ==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:m+j2xJADzzJEQHLb4Wx+AzM=,iv:gCFk/KIzQEWYaOOJO6imbwSNl6JRszPTaupYLgwCVfM=,tag:hHflrW3hVOs2OGx7vD9UQw==,type:str]
    PUBLIC_IPV6_PREFIX: ENC[AES256_GCM,data:qR2p8D4DlKKYxUuaeiA=,iv:xcMaI0gLC2fyP60JzYThD/OFt5KXm9V/I+iIldNmPxU=,tag:9zu3Ae/rigIOPzNZUvjd/A==,type:str]
    CILIUM_LB_CIDR_V6: ENC[AES256_GCM,data:5edHACkfHFH3WfWV6A3pg619fKc=,iv:Q/2CTFirJsl6SMheS9bFV8iZPIrnLH91+QPL21DN27c=,tag:iujnKEsoLv+GVmrhxFhCVg==,type:str]
    CILIUM_BGP_PEER_V6: ENC[AES256_GCM,data:FYRf0rrrFFBQ3iNaihFelYI=,iv:cA+q7t6WUd3woKNPOE7EOtm/deGBWHnbUXM9Ol7b3G8=,tag:l5uSyAMQ8YCEjIzNFpXnKw==,type:str]
    INGRESS_EXT_LB_IP_V6: ENC[AES256_GCM,data:2FjrRC9hkKny91+5Y4j3oLnEsxI=,iv:TZgLboJyMYfCQb+cgBHBtX7Oy58cIk5wX0jJhq8g2/I=,tag:JaRa23HtiSnhXpUx5Ap5Yg==,type:str]
    INGRESS_INT_LB_IP_V6: ENC[AES256_GCM,data:OnpxO553CjbACIY6+VCxAufNXmM=,iv:rk6vay80L9it1qXEucXksK/axF60zBoGZn/XegL8WuY=,tag:8Is5K5ngxCvUf6YSb23ykg==,type:str]
    INGRESS_HOME_LB_IP_V6: ENC[AES256_GCM,data:pQeRWFND96wzpQtoXtlNHRQbP38=,iv:akENJHKuAMkg4ctt2JVfdKOx0oTAiXmA03nCqGMYM7A=,tag:yomA1QYd76n2PriVtvPJzg==,type:str]
    ENVOY_INT_LB_IP_V6: ENC[AES256_GCM,data:lu34mD/u8fl+sJeFyuCD1uwb5ck=,iv:cjdf9n37s+kbxC5ptbxx9WYfl6HaK6HJBUhY0cPeSJo=,tag:UP4GTUfdW7nTlFMKRvnK2w==,type:str]
    ENVOY_EXT_LB_IP_V6: ENC[AES256_GCM,data:3Cvz4NhNXhgMgsZ1VtFmxYVGIEM=,iv:NNaCiATsHH6YbIe+q1OS7p8p0suw65AuLyY4XKSs9rM=,tag:tAznRKutxQPDwc0ayr8RaA==,type:str]
    SATISFACTORY_LB_IP_V6: ENC[AES256_GCM,data:XwCVB2ZaBUZShHWCDnJBN1C8/Q==,iv:xGq3P+UAb70jNIb9OSejdseo5seuynUmnPuakhhW/+g=,tag:QLF13X3+y1iofQz4RIIO1g==,type:str]
    SATISFACTORY2_LB_IP_V6: ENC[AES256_GCM,data:Br13eHw4WyfuIjRq6k8cuT4UWA==,iv:Soydx56AMsHBRd3s7LsjQzSogxAXxBRdF/9K82omMTI=,tag:GWlcjrR0fDJQJVmZ+KqdWA==,type:str]
sops:
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYi9UQm54TGt6OFFXTVE5
            YTVTVWVpdDNENEFYWHIzK292aHVwaktReTJBCkhQR05lU0V4WGcwUGtDblByUUhm
            U3R2aXd5THFYMHYybFo0UnhnN1dKU1UKLS0tIGVlRkt3a3JDUXl5TEZuTnRBRk53
            a0dmcnJZL3ovWUJrUG9FQ2NzKzhZZUUKqMcRHZoLl16ZDzGCijr2A0fOeQs20Hbh
            jHF+9Xtf+LBwB7xvlohfZy7W6OrO2BKOJs3DWaF2m/U2TWO8cIMcRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T23:41:12Z"
    mac: ENC[AES256_GCM,data:Twaohqaayjk88xzo5V5H5tvYeojdKVYFic8hymhvJDJEns6Sj/KNuuOgzfUXa2uY4ZTcgpbqilBza0fdrbVHe5Mn1FzEDglyYLjsp7BOmp+bafl7VOyvZDeZq5gAEhJ/R9Q9lONjmhCcuxOiDgrQdRARneuhrrHUoZxYZm5+7YI=,iv:X/0U57l4KeHlEP6FKE43s6C33yG+/P8Pl4yeNC17eNU=,tag:tr20EKy276/awW18lNd5MA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
