apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:Kea8IfCohNAan6+WJKw=,iv:PRA78Vo3gfMB+wu3oPY06dziL2cNZEA+rLm6CY99Xc8=,tag:kOqCwZHe92ByYn6mo2Db/Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:936ab2jlBkhIGsUh0to=,iv:1GLdEUM0JQrLk1PxRjAHadR2pPNCrbD3NTw+XPDV0kw=,tag:2uQO+0H2bdRlT9U58d98dw==,type:str]
    SECRET_DOMAIN_INTERNAL: ENC[AES256_GCM,data:U9D/LkaKUOvl8fKUwt4=,iv:rWZCBwodZiAY9FduWpqljgoC6lh57AgBHLAuPsvqIqY=,tag:bdp5OFTuHnbSyj38uo0a+w==,type:str]
    PRIVATE_DOMAIN_HOME: ENC[AES256_GCM,data:zhAAZwBN1W+JVN0b5Mk=,iv:HVVuLboHGClarnXTKzqRQhPdClsRr9rPhypvqOLQ48g=,tag:FT20DWKuHjkMi6L0lh08Qg==,type:str]
    PRIVATE_EMAIL: ENC[AES256_GCM,data:gcOm7nWa+XPhBMHEAKSzCn9m54cZQA==,iv:r1DPuElai1eb5tNV3xHqdP9eLPHRoE3UMtky23ax3Jg=,tag:yrEw0VgcWLodku3XXA2LVQ==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:m+j2xJADzzJEQHLb4Wx+AzM=,iv:gCFk/KIzQEWYaOOJO6imbwSNl6JRszPTaupYLgwCVfM=,tag:hHflrW3hVOs2OGx7vD9UQw==,type:str]
    PUBLIC_IPV6_PREFIX: ENC[AES256_GCM,data:qR2p8D4DlKKYxUuaeiA=,iv:xcMaI0gLC2fyP60JzYThD/OFt5KXm9V/I+iIldNmPxU=,tag:9zu3Ae/rigIOPzNZUvjd/A==,type:str]
    CILIUM_LB_CIDR_V6: ENC[AES256_GCM,data:dJiG5plyiOih+nSTf3PS0HGHGoT7KQ==,iv:bgW45YBDf6RGA1zE+5sYdhxhVrh+O1gpMWdJYlBvRcc=,tag:P5mXocl9QbC5PDBQiNVCHw==,type:str]
    CILIUM_BGP_PEER_V6: ENC[AES256_GCM,data:FYRf0rrrFFBQ3iNaihFelYI=,iv:cA+q7t6WUd3woKNPOE7EOtm/deGBWHnbUXM9Ol7b3G8=,tag:l5uSyAMQ8YCEjIzNFpXnKw==,type:str]
    INGRESS_EXT_LB_IP_V6: ENC[AES256_GCM,data:X27k6eTZBpbZs9E/WvLBRtBM6ARGl58=,iv:C/eNDOf/nJVcKx0ER1ZiqGb+PS7Il42K7Upskfn29q0=,tag:3B0cTWPp/rDapR+0Gi93DQ==,type:str]
    INGRESS_INT_LB_IP_V6: ENC[AES256_GCM,data:736suItIMEEdM1XaZvJjAirBDNmUuVM=,iv:33W1FsWAZ2oaPLsxceZJITNqVUFTMnAPH7HkSLkCBs4=,tag:gdTqovLrNAC5MMKTZ/GWKA==,type:str]
    INGRESS_HOME_LB_IP_V6: ENC[AES256_GCM,data:LyR1uaAG9/TBFzwHyl6Gn57M98+sMwU=,iv:w+0B0lewTKIKJdBM9kbmSfE8SoAzCBFOqZ57ARBqeJk=,tag:DgE4wBYvD7Z85SsRo65thQ==,type:str]
    ENVOY_INT_LB_IP_V6: ENC[AES256_GCM,data:hqh/2IbJJeA1MF+lP+RGGk/OUpV22JQ=,iv:zSFdj/CDoS4vGf7wT8JR/3zllPCJAUlBuIsb3IKBEWk=,tag:GwSkly9W8z71Og2LKVI57A==,type:str]
    ENVOY_EXT_LB_IP_V6: ENC[AES256_GCM,data:sHHSesOyl91kTF+37jAeQMcGplFAj5c=,iv:FD4nGyFXBMdmoqmDv0bHLCJQ2TaT0wy3ahk3mQq9tAA=,tag:LWbMsHXDw3eK76cKOS/Ahg==,type:str]
    SATISFACTORY_LB_IP_V6: ENC[AES256_GCM,data:Ak4vT6eY7YKH9TL0FJOnmXE9TkObrw==,iv:WmfMZ7WPG/1+VPw4o1gyOWHZfK2ellGiGzu9JVEanYs=,tag:++oFcAHBCGRVOPqHHsG7+w==,type:str]
    SATISFACTORY2_LB_IP_V6: ENC[AES256_GCM,data:j13knm/+awNuJUazaxDv8wQTJXJXPQ==,iv:LAFs4li+VFv1tIc63N9EBFeBvgs3DKNO4l92wbpYzLE=,tag:HBRtXpgX52TirFX0RFZDQA==,type:str]
sops:
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYi9UQm54TGt6OFFXTVE5
            YTVTVWVpdDNENEFYWHIzK292aHVwaktReTJBCkhQR05lU0V4WGcwUGtDblByUUhm
            U3R2aXd5THFYMHYybFo0UnhnN1dKU1UKLS0tIGVlRkt3a3JDUXl5TEZuTnRBRk53
            a0dmcnJZL3ovWUJrUG9FQ2NzKzhZZUUKqMcRHZoLl16ZDzGCijr2A0fOeQs20Hbh
            jHF+9Xtf+LBwB7xvlohfZy7W6OrO2BKOJs3DWaF2m/U2TWO8cIMcRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T06:42:11Z"
    mac: ENC[AES256_GCM,data:m9xdD6Os0YQPGdOzOfDde2DpuyLbXIowqqPmFEevYIE07yiVcvYA5lFpsGCTOHPF08SsvsWJdqghzx1YBhux2vYvUh3zxSY/6q/Cne2afZGDHt0gyGGV4/wOcDrOddhdLo1t46Hv7x1U7ZCy0vHw7iWjg6lvz/4OaQeOvu/yNsw=,iv:amIeoC45JgjZ1b01kVCkRUe7STu3RWBUupPPGUAh+e4=,tag:1bYonVB0iNgPYxP3u3xvig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
