---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller-charts.yaml
  - ./angelnu-charts.yaml
  - ./backube-charts.yaml
  - ./bitnami-charts.yaml
  - ./bjw-s-charts.yaml
  - ./cilium-charts.yaml
  - ./cloudnative-pg-charts.yaml
  - ./deliveryhero-charts.yaml
  - ./democratic-csi-charts.yaml
  - ./external-dns-charts.yaml
  - ./external-secrets-charts.yaml
  - ./fairwinds-charts.yaml
  - ./grafana-charts.yaml
  - ./hajimari-charts.yaml
  - ./ingress-nginx-charts.yaml
  - ./intel-charts.yaml
  - ./jetstack-charts.yaml
  - ./kubernetes-sigs-descheduler-charts.yaml
  - ./kyverno-charts.yaml
  - ./lwolf-charts.yaml
  - ./metrics-server-charts.yaml
  - ./node-feature-discovery-charts.yaml
  - ./piraeus-charts.yaml
  - ./postfinance-charts.yaml
  - ./prometheus-community-charts.yaml
  - ./rook-ceph-charts.yaml
  - ./stakater-charts.yaml
  - ./weave-gitops-charts.yaml
  - ./windmill-charts.yaml
  - ./nvidia-device-plugin-charts.yaml
  - ./k8tz-charts.yaml
  - ./jacobcolvin-charts.yaml
  - ./itzg-charts.yaml
  - ./crystalnet-charts.yaml
  - ./mariadb-operator-charts.yaml
  - ./crunchydata-charts.yaml
  - ./tailscale-charts.yaml
  - ./coredns-charts.yaml
  - ./stevehipwell-charts.yaml
  - ./spegel-charts.yaml
  - ./1password-charts.yaml
  - ./agones-charts.yaml
  - ./shulker-charts.yaml
  - ./openebs-charts.yaml
  - ./k8s-gateway-charts.yaml
  - ./ollama-charts.yaml
  - ./open-webui-charts.yaml
  - ./k8sgpt-charts.yaml
