---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot-ipv6
spec:
  config: |-
    {
      "cniVersion": "1.1.0",
      "name": "multus-iot-ipv6",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.30",
          "mode": "bridge",
          "ipam": {
            "type": "dhcp"
          }
        },
        {
          "type": "tuning",
          "sysctl": {
            "net.ipv6.conf.net1.forwarding": "1",
            "net.ipv6.conf.net1.accept_ra": "2",
            "net.ipv6.conf.net1.accept_ra_rt_info_max_plen": "64"
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
