---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: terraform
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/spiceratops/manifests/terraform
  ref:
    tag: master
