---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: donetick
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: donetick-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Donetick
        DT_JWT_SECRET: "{{ .DT_JWT_SECRET }}"
        # OIDC
        DT_OAUTH2_CLIENT_ID: "{{ .DONETICK_CLIENT_ID }}"
        DT_OAUTH2_CLIENT_SECRET: "{{ .DONETICK_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: donetick
    - extract:
        key: pocket-id
