---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}" # Must start with sk-
        LITELLM_SALT_KEY: "{{ .LITELLM_SALT_KEY }}" # Must start with sk-
        GOOGLE_API_KEY: "{{ .GEMINI_API_KEY }}"
        # Postgres Init
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_DBNAME: litellm
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.databases.svc.cluster.local/litellm"
  dataFrom:
    - extract:
        key: litellm
    - extract:
        key: cloudnative-pg
