---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: karakeep-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        # Oauth
        OAUTH_CLIENT_ID: "{{ .KARAKEEP_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .KARAKEEP_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: karakeep
