---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sops-age
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sops-age-secret
    creationPolicy: Owner
    template:
      data:
        age.agekey: "{{ .SOPS_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: sops
