---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
# configMapGenerator:
#   - name: cilium-helm-values
#     files:
#       - ./resources/values.yaml
# generatorOptions:
#   disableNameSuffixHash: true
