---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - ./cloudnative-pg/ks.yaml
  - ./pgadmin/ks.yaml
  - ./dragonfly/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
