---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clickops
resources:
  - ./clickops/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
