---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./wyoming-piper/ks.yaml
  - ./wyoming-whisper/ks.yaml
  - ./wyoming-openwakeword/ks.yaml
  - ./guacamole/ks.yaml
  - ./wyoming-glados/ks.yaml
  - ./scrypted/ks.yaml
