---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./_pvc/ks.yaml
  - ./wyoming-piper/ks.yaml
  - ./wyoming-whisper/ks.yaml
  - ./wyoming-openwakeword/ks.yaml
  # - ./guacamole/ks.yaml
  - ./glados/ks.yaml
  # - ./scrypted/ks.yaml
  - ./go2rtc/ks.yaml
  - ./esphome/ks.yaml
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./zigbee2mqtt/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
