---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./helmrelease.yaml
  - ./volsync.yaml
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - ./resources/mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true
