---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./external-secrets/ks.yaml
  - ./authelia/ks.yaml
  - ./lldap/ks.yaml
components:
  - ../../components/alerts
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
