---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./_pvc/ks.yaml
  - ./ollama/ks.yaml
  - ./open-webui/ks.yaml
  - ./perplexica/ks.yaml
  - ./swarmui/ks.yaml
