---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./_pvc/ks.yaml
  # - ./ollama/ks.yaml
  # - ./open-webui/ks.yaml
  # - ./swarmui/ks.yaml
  - ./qdrant/ks.yaml
  - ./litellm/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
  - ../../components/alerts
