---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - ./external-secrets/ks.yaml
components:
  - ../../components/repos
  - ../../components/substitutions
