---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./excalidraw/ks.yaml
  - ./libreddit/ks.yaml
  - ./nostr-relay/ks.yaml
  # - ./shlink/ks.yaml
  - ./mealie/ks.yaml
  - ./miniflux/ks.yaml
  - ./windmill/ks.yaml
  - ./actual/ks.yaml
  - ./immich/ks.yaml
  - ./wallabag/ks.yaml
  - ./linkding/ks.yaml
  - ./homebox/ks.yaml
  - ./homepage/ks.yaml
  # - ./whoogle/ks.yaml
  - ./drawio/ks.yaml
  - ./paperless/ks.yaml
  - ./ocis/ks.yaml
  - ./libmedium/ks.yaml
  - ./hajimari/ks.yaml
  - ./wallos/ks.yaml
  - ./mmp/ks.yaml
  - ./hoarder/ks.yaml
  - ./searxng/ks.yaml
