---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./_pvc/ks.yaml
  - ./excalidraw/ks.yaml
  - ./redlib/ks.yaml
  - ./mealie/ks.yaml
  - ./actual/ks.yaml
  - ./immich/ks.yaml
  - ./homebox/ks.yaml
  - ./homepage/ks.yaml
  - ./drawio/ks.yaml
  - ./paperless/ks.yaml
  - ./ocis/ks.yaml
  - ./libmedium/ks.yaml
  # - ./hajimari/ks.yaml
  - ./wallos/ks.yaml
  - ./karakeep/ks.yaml
  - ./searxng/ks.yaml
  # - ./n8n/ks.yaml
  - ./shelfmark/ks.yaml
  - ./donetick/ks.yaml
  - ./freetar/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
  - ../../components/alerts
