---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ./atuin/ks.yaml
  - ./cyberchef/ks.yaml
  - ./it-tools/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
  - ../../components/replacements
