---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.11.18
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 30m
  values:
    fullnameOverride: victoria-logs
    retentionPeriod: 14d
    server:
      persistentVolume:
        enabled: true
        storageClassName: ${CLUSTER_STORAGE_BLOCK}
        size: 20Gi
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: observability
      labels:
        grafana_dashboard: "1"
