---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        QUI__SESSION_SECRET: "{{ .QUI_SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: qui
