---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        QUI__SESSION_SECRET: "{{ .QUI_SESSION_SECRET }}"
        QUI__OIDC_CLIENT_ID: "{{ .QUI_CLIENT_ID }}"
        QUI__OIDC_CLIENT_SECRET: "{{ .QUI_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: qui
    - extract:
        key: pocket-id
