---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudflared/ks.yaml
  - ./echo-server/ks.yaml
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./multus/ks.yaml
  - ./tailscale-operator/ks.yaml
  - ./envoy-gateway/ks.yaml
components:
  - ../../components/alerts
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
