---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-operator/ks.yaml
  - ./flux-webhooks/ks.yaml
  - ./headlamp/ks.yaml
components:
  - ../../components/repos
  - ../../components/substitutions
