---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: slskd-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SLSKD_SLSK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
  dataFrom:
    - extract:
        key: slskd
