---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  # - ./tuppr/ks.yaml
  - ./keda/ks.yaml
  - ./fstrim/ks.yaml
  - ./csi-driver-nfs/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
  - ../../components/alerts
