---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./system-upgrade-controller/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
