---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  decryption:
    provider: sops
  deletionPolicy: WaitForTermination
  interval: 1h
  path: ./kubernetes/apps
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  patches:
    - # Update Cert-manager replicas
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          patches:
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRelease
                metadata:
                  name: not-used
                spec:
                  values:
                    webhook:
                      replicaCount: 2
                      podDisruptionBudget:
                        enabled: true
              target:
                kind: HelmRelease
                name: cert-manager
      target:
        kind: Kustomization
        name: cert-manager
    - # Update Cilium Operator replicas
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          patches:
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRelease
                metadata:
                  name: not-used
                spec:
                  values:
                    cluster:
                      name: main
                    operator:
                      replicas: 2
              target:
                kind: HelmRelease
                name: cilium
      target:
        kind: Kustomization
        name: cilium
    - # Update CoreDNS replicas
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          patches:
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRelease
                metadata:
                  name: not-used
                spec:
                  values:
                    replicaCount: 3
              target:
                kind: HelmRelease
                name: coredns
      target:
        kind: Kustomization
        name: coredns
    - # Update External-Secrets replicas
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          patches:
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRelease
                metadata:
                  name: not-used
                spec:
                  values:
                    webhook:
                      replicaCount: 2
              target:
                kind: HelmRelease
                name: external-secrets
      target:
        kind: Kustomization
        name: external-secrets
    - # Add Sops decryption to all Kustomizations
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
    - # Add postBuild to all Kustomizations
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-settings
                optional: false
              - kind: Secret
                name: cluster-secrets
                optional: false
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
