---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./_pvc/ks.yaml
  - ./romm/ks.yaml
  - ./satisfactory/ks.yaml
  - ./satisfactory2/ks.yaml
  - ./minecraft/ks.yaml
  - ./dnd-tools/ks.yaml
  - ./foundryvtt/ks.yaml
components:
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
